INSERT INTO users (email, password, city, joined_on, img_url) VALUES
  ('foo@bar.com', '123', 'Oakland', '10/10/2017', 'http://lorempixel.com/output/cats-q-c-400-400-5.jpg'),
  ('cat@damon.com', '123', 'San Francisco', '09/10/2006', 'http://lorempixel.com/output/cats-q-c-400-400-7.jpg'),
  ('diane@kitten.com', '123', 'San Francisco', '04/10/2016', 'http://lorempixel.com/output/cats-q-c-400-400-8.jpg');

INSERT INTO cities (name, img_url) VALUES
  ('Oakland', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Oldoakland02262006.JPG/1920px-Oldoakland02262006.JPG'),
  ('San Francisco', 'http://www.sftravel.com/sites/sftraveldev.prod.acquia-sites.com/files/landmark-images/golden-gate_web.jpg'),
  ('Los Angeles', 'https://images2.laweekly.com/imager/u/original/5620760/6544632161_33cba3f3e4_o.jpg');

INSERT INTO posts (user_id, city_id, title, body, posted_on) VALUES
  (1, 1, 'OMG Oaklalala is a city in the east bae', 'Curl into a furry donut hide at bottom of staircase to trip human give attitude have a lot of grump in yourself because you can''t forget to be grumpy and not be like king grumpy cat so need to chase tail. Claw at curtains stretch and yawn nibble on tuna ignore human bite human hand put toy mouse in food bowl run out of litter box at full speed but damn that dog . Use lap as chair meow wake up wander around the house making large amounts of noise jump on top of your human''s bed and fall asleep again. Eat from dog''s food claw drapes. Lick the curtain just to be annoying sit on the laptop. Behind the couch my left donut is missing, as is my right, and meow for food, then when human fills food dish, take a few bites of food and continue meowing. Meoooow lick yarn hanging out of own butt. Loves cheeseburgers scratch the box.', '09/10/2006'),
  (1, 2, 'SF blah, something something dark side', 'Freak human out make funny noise mow mow mow mow mow mow success now attack human this human feeds me, i should be a god, tuxedo cats always looking dapper sleep on dog bed, force dog to sleep on floor or scamper sleep on dog bed, force dog to sleep on floor. Lick the plastic bag cats are fats i like to pets them they like to meow back. Cats go for world domination. Ignore the squirrels, you''ll never catch them anyway all of a sudden cat goes crazy, going to catch the red dot today going to catch the red dot today hiding behind the couch until lured out by a feathery toy. Flee in terror at cucumber discovered on floor eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap.', '09/10/2017'),
  (3, 1, 'San Fran has some bart stops or something', 'Human is washing you why halp oh the horror flee scratch hiss bite thinking longingly about tuna brine chase imaginary bugs, so refuse to drink water except out of someone''s glass mew. Scratch the furniture jump five feet high and sideways when a shadow moves you call this cat food. Lick arm hair unwrap toilet paper drool, for have my breakfast spaghetti yarn yet bathe private parts with tongue then lick owner''s face lies down , or plays league of legends. Attack dog, run away and pretend to be victim. Cat mojo lick butt.', '10/10/2017'),
  (2, 1, 'Oakland has some bart stops or something', 'Eat all the power cords chase laser for soft kitty warm kitty little ball of furr, find a way to fit in tiny box cats making all the muffins jump on human and sleep on her all night long be long in the bed, purr in the morning and then give a bite to every human around for not waking up request food, purr loud scratch the walls, the floor, the windows, the humans small kitty warm kitty little balls of fur. Pooping rainbow while flying in a toasted bread costume in space vommit food and eat it again for your pillow is now my pet bed for if it smells like fish eat as much as you wish.', '04/10/2016'),
  (2, 3, 'Attack the dog then pretend like nothing happened', 'Leave fur on owners clothes thug cat slap owner''s face at 5am until human fills food dish spend all night ensuring people don''t sleep sleep all day and chase red laser dot stare at guinea pigs and meow go back to sleep owner brings food and water tries to pet on head, so scratch get sprayed by water because bad cat. Stick butt in face i just saw other cats inside the house and nobody ask me before using my litter box. Meowwww. Cough hairball on conveniently placed pants bleghbleghvomit my furball really tie the room together Gate keepers of hell human is washing you why halp oh the horror flee scratch hiss bite and make meme, make cute face. Flop over climb a tree, wait for a fireman jump to fireman then scratch his face you call this cat food peer out window, chatter at birds, lure them to mouth cough furball fooled again thinking the dog likes me. Cat snacks.', '11/10/2017'),
  (3, 3, 'If it smells like fish eat as much as you wish', 'Sweet beast lie in the sink all day toy mouse squeak roll over. Run outside as soon as door open. Jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed poop in litter box, scratch the walls or kitty scratches couch bad kitty inspect anything brought into the house brown cats with pink ears for man running from cops stops to pet cats, goes to jail love and coo around boyfriend who purrs and makes the perfect moonlight eyes so i can purr and swat the glittery gleaming yarn to him (the yarn is from a $125 sweater). Kitty power i just saw other cats inside the house and nobody ask me before using my litter box. Need to chase tail meoooow i''m going to lap some water out of my master''s cup meow for hopped up on catnip. Steal the warm chair right after you get up chew foot, or ask for petting.', '10/31/2017');
